name: din0xTpa
version: 1
author: din0x
main: me.din0x.din0xTpa.Din0xTpa
api-version: 1.18
commands:
  tpa:
    description: Teleport to player.
    usage: /<command> <player>

  tpaaccept:
    description: Accept teleport request.
    usage: /<command> <player>

  tpadeny:
    description: Reject teleport request.
    usage: /<command> <player>

  tpacancel:
    description: Cancel releport request.
    usage: /<command> <player>